import { useEffect, useState } from 'react';
import { Download, Eye, Loader2, RefreshCcw, Search, Trash2, X } from 'lucide-react';
import { hireFromUsService } from '../../services/hireFromUsService';
import '../../styles/admin.css';

const statuses = ['New', 'Contacted', 'Requirement Discussed', 'Candidates Shared', 'Interview Scheduled', 'Hiring in Progress', 'Closed', 'Not Interested'];
const priorities = ['Low', 'Medium', 'High'];
const editable = ['recruiter_name', 'work_email', 'phone', 'designation', 'company_name', 'company_website', 'industry', 'company_location', 'job_role', 'number_of_openings', 'experience_required', 'required_skills', 'work_mode', 'job_location', 'salary_range', 'hiring_timeline', 'job_description', 'jd_url'];
const labels = { recruiter_name: 'Recruiter', work_email: 'Work Email', phone: 'Phone', designation: 'Designation', company_name: 'Company', company_website: 'Company Website', industry: 'Industry', company_location: 'Company Location', job_role: 'Job Role', number_of_openings: 'Openings', experience_required: 'Experience', required_skills: 'Required Skills', work_mode: 'Work Mode', job_location: 'Job Location', salary_range: 'Salary Range', hiring_timeline: 'Hiring Timeline', job_description: 'Job Description', jd_url: 'JD Link' };
const emptyFilters = { search: '', status: '', priority: '', company: '', role: '', fromDate: '', toDate: '' };

export default function HireFromUsList() {
  const [leads, setLeads] = useState([]), [counts, setCounts] = useState({ total: 0, fresh: 0, active: 0, closed: 0 }), [loading, setLoading] = useState(true), [filters, setFilters] = useState(emptyFilters), [applied, setApplied] = useState(emptyFilters), [selected, setSelected] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const load = async (current = applied) => {
    setLoading(true); setError('');
    const [{ data, error: resultError }, { data: summary, error: statsError }] = await Promise.all([hireFromUsService.getLeads(current), hireFromUsService.getSummary()]);
    if (resultError || statsError) { setError('Could not load hiring leads. Check the hire_from_us_leads table and admin access policies.'); setLeads([]); }
    else { setLeads(data || []); setCounts(summary); }
    setLoading(false);
  };
  useEffect(() => { load(); }, [applied]);
  const updateFilter = e => setFilters(v => ({ ...v, [e.target.name]: e.target.value }));
  const apply = e => { e.preventDefault(); setApplied({ ...filters }); };
  const updateLead = async (id, changes) => { setBusy(true); const { error: updateError } = await hireFromUsService.updateLead(id, changes); if (updateError) setError('Could not save the lead. Please try again.'); else { if (selected?.id === id) setSelected(v => ({ ...v, ...changes })); await load(); } setBusy(false); };
  const exportCsv = () => {
    const cols = ['created_at', ...editable, 'status', 'priority', 'assigned_to', 'admin_notes', 'last_contacted_at'];
    const q = value => `"${String(value ?? '').replaceAll('"', '""')}"`;
    const text = [cols.join(','), ...leads.map(row => cols.map(k => q(row[k])).join(','))].join('\r\n');
    const url = URL.createObjectURL(new Blob([text], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = `hire_from_us_${new Date().toISOString().slice(0, 10)}.csv`; a.click(); URL.revokeObjectURL(url);
  };
  const remove = async () => { if (!selected || !window.confirm(`Delete the hiring enquiry from ${selected.company_name}?`)) return; setBusy(true); const { error: removeError } = await hireFromUsService.deleteLead(selected.id); if (removeError) setError('Could not delete this lead.'); else { setSelected(null); await load(); } setBusy(false); };
  const stat = (label, value) => <div className="admin-stat-card" key={label}><div className="admin-stat-details"><div className="admin-stat-label">{label}</div><div className="admin-stat-value">{value}</div></div></div>;

  return <div className="admin-page">
    <div className="admin-page-header"><div><h1 className="admin-page-title">Hire From Us</h1><p className="admin-page-subtitle">Manage company hiring requirements and recruiter leads</p></div><div className="admin-header-actions"><button className="admin-btn admin-btn-secondary" onClick={exportCsv}><Download size={16}/> Export CSV</button><button className="admin-btn admin-btn-secondary" onClick={() => load()} title="Refresh"><RefreshCcw size={16}/></button></div></div>
    {error && <div className="admin-alert error">{error}</div>}
    <div className="admin-stats-grid" style={{ marginBottom: 24, display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(180px,1fr))', gap: 16 }}>{stat('Total Hiring Enquiries', counts.total)}{stat('New Enquiries', counts.fresh)}{stat('Active Requirements', counts.active)}{stat('Closed Requirements', counts.closed)}</div>
    <div className="admin-card">
      <form onSubmit={apply} className="hire-admin-filters"><label><span>Search</span><div className="hire-admin-search"><Search size={15}/><input className="admin-input" name="search" value={filters.search} onChange={updateFilter} placeholder="Company, recruiter, role or email" /></div></label>
        <label><span>Status</span><select className="admin-input" name="status" value={filters.status} onChange={updateFilter}><option value="">All statuses</option>{statuses.map(s => <option key={s}>{s}</option>)}</select></label><label><span>Priority</span><select className="admin-input" name="priority" value={filters.priority} onChange={updateFilter}><option value="">All priorities</option>{priorities.map(p => <option key={p}>{p}</option>)}</select></label>
        <label><span>Company</span><input className="admin-input" name="company" value={filters.company} onChange={updateFilter} placeholder="Company name" /></label><label><span>Role</span><input className="admin-input" name="role" value={filters.role} onChange={updateFilter} placeholder="Job role" /></label><label><span>From</span><input className="admin-input" type="date" name="fromDate" value={filters.fromDate} onChange={updateFilter}/></label><label><span>To</span><input className="admin-input" type="date" name="toDate" value={filters.toDate} onChange={updateFilter}/></label><button className="admin-btn admin-btn-primary" type="submit">Apply filters</button>
      </form>
      <div className="admin-table-container" style={{ overflowX: 'auto' }}><table className="admin-table hire-admin-table"><thead><tr>{['Company', 'Recruiter', 'Role', 'Openings', 'Experience', 'Location', 'Hiring Timeline', 'Status', 'Priority', 'Submitted', 'Actions'].map(x => <th key={x}>{x}</th>)}</tr></thead><tbody>
        {loading ? <tr><td colSpan="11" style={{ textAlign: 'center', padding: 40 }}><Loader2 className="spinner"/> Loading hiring enquiries...</td></tr> : leads.length === 0 ? <tr><td colSpan="11" className="admin-empty-state">No hiring enquiries found.</td></tr> : leads.map(lead => <tr key={lead.id} onClick={() => setSelected(lead)} className="hire-admin-row"><td><strong>{lead.company_name}</strong><small>{lead.industry}</small></td><td>{lead.recruiter_name}<small>{lead.work_email}</small></td><td>{lead.job_role}</td><td>{lead.number_of_openings}</td><td>{lead.experience_required}</td><td>{lead.job_location}</td><td>{lead.hiring_timeline}</td><td><span className={`admin-badge ${lead.status === 'New' ? 'badge-new' : ['Closed', 'Not Interested'].includes(lead.status) ? 'badge-closed' : 'badge-contacted'}`}>{lead.status}</span></td><td><span className={`admin-badge ${lead.priority === 'High' ? 'badge-high' : lead.priority === 'Low' ? 'badge-low' : 'badge-medium'}`}>{lead.priority}</span></td><td>{new Date(lead.created_at).toLocaleDateString()}</td><td><button className="admin-action-btn" onClick={e => { e.stopPropagation(); setSelected(lead); }} title="View lead"><Eye size={17}/></button></td></tr>)}
      </tbody></table></div><p className="hire-admin-count">Showing {leads.length} hiring enquiries</p>
    </div>
    {selected && <div className="hire-admin-overlay" onMouseDown={e => { if (e.target === e.currentTarget && !busy) setSelected(null); }}><aside className="hire-admin-drawer"><header><div><h2>Hiring enquiry details</h2><p>Submitted {new Date(selected.created_at).toLocaleString()}</p></div><button className="admin-icon-btn" onClick={() => setSelected(null)} aria-label="Close"><X size={20}/></button></header>
      <div className="hire-admin-content"><section className="hire-admin-editor"><h3>Lead status</h3><label>Status<select className="admin-input" value={selected.status} disabled={busy} onChange={e => updateLead(selected.id, { status: e.target.value, ...(e.target.value === 'Contacted' ? { last_contacted_at: new Date().toISOString() } : {}) })}>{statuses.map(s => <option key={s}>{s}</option>)}</select></label><label>Priority<select className="admin-input" value={selected.priority} disabled={busy} onChange={e => updateLead(selected.id, { priority: e.target.value })}>{priorities.map(p => <option key={p}>{p}</option>)}</select></label><label>Assigned to<input className="admin-input" value={selected.assigned_to || ''} onChange={e => setSelected(v => ({ ...v, assigned_to: e.target.value }))} onBlur={e => updateLead(selected.id, { assigned_to: e.target.value || null })}/></label></section>
      {[['Contact details', editable.slice(0, 4)], ['Company details', editable.slice(4, 8)], ['Hiring requirement', editable.slice(8)]].map(([group, keys]) => <section className="hire-admin-editor" key={group}><h3>{group}</h3>{keys.map(key => <label key={key}>{labels[key]}{key === 'job_description' ? <textarea className="admin-input" rows="4" value={selected[key] || ''} onChange={e => setSelected(v => ({ ...v, [key]: e.target.value }))} onBlur={e => updateLead(selected.id, { [key]: e.target.value })}/> : <input className="admin-input" value={selected[key] || ''} onChange={e => setSelected(v => ({ ...v, [key]: e.target.value }))} onBlur={e => updateLead(selected.id, { [key]: e.target.value || null })}/>}</label>)}</section>)}
      <section className="hire-admin-editor"><h3>Internal notes</h3><label>Notes (private)<textarea className="admin-input" rows="5" value={selected.admin_notes || ''} onChange={e => setSelected(v => ({ ...v, admin_notes: e.target.value }))} onBlur={e => updateLead(selected.id, { admin_notes: e.target.value || null })}/></label></section>
      </div><footer><button className="admin-btn admin-btn-secondary" disabled={busy} onClick={remove}><Trash2 size={16}/> Delete lead</button><button className="admin-btn admin-btn-primary" onClick={() => { setSelected(null); load(); }}>Done</button></footer>
    </aside></div>}
    <style>{`.hire-admin-filters{display:flex;align-items:end;gap:12px;flex-wrap:wrap;margin-bottom:20px}.hire-admin-filters label,.hire-admin-editor label{display:flex;flex-direction:column;gap:5px;min-width:130px;flex:1}.hire-admin-filters label>span,.hire-admin-editor label{font-size:12px;color:#59665c}.hire-admin-search{position:relative}.hire-admin-search svg{position:absolute;left:10px;top:11px;color:#9ca3af}.hire-admin-search input{padding-left:32px;width:100%}.hire-admin-table{min-width:1120px}.hire-admin-table td small{display:block;color:#778177;font-size:11px;margin-top:3px}.hire-admin-row{cursor:pointer}.hire-admin-row:hover{background:#f8faf9}.hire-admin-count{margin:14px 4px 0;color:#68766d;font-size:13px}.hire-admin-overlay{position:fixed;z-index:2000;inset:0;background:#0b151080;display:flex;justify-content:flex-end}.hire-admin-drawer{width:min(680px,100%);height:100%;background:#f8fafc;display:flex;flex-direction:column;box-shadow:-10px 0 40px #0002}.hire-admin-drawer>header,.hire-admin-drawer>footer{padding:17px 22px;background:#fff;border-bottom:1px solid #e5e7eb;display:flex;align-items:center;justify-content:space-between;gap:12px}.hire-admin-drawer>header h2{font-size:18px}.hire-admin-drawer>header p{color:#718071;font-size:12px;margin-top:3px}.hire-admin-drawer>footer{border-top:1px solid #e5e7eb;border-bottom:0}.hire-admin-content{padding:18px;overflow:auto}.hire-admin-editor{padding:17px;background:#fff;border:1px solid #e5e7eb;border-radius:9px;margin-bottom:14px;display:grid;grid-template-columns:1fr 1fr;gap:12px}.hire-admin-editor h3{grid-column:1/-1;font-size:14px}.hire-admin-editor label{font-size:11px}.hire-admin-editor textarea{resize:vertical}.hire-admin-editor .admin-input{font-size:13px}.admin-badge.badge-new{background:#dbeafe;color:#1e40af}.admin-badge.badge-contacted{background:#fef3c7;color:#b45309}.admin-badge.badge-closed{background:#f3f4f6;color:#374151}.admin-badge.badge-high{background:#fee2e2;color:#b91c1c}.admin-badge.badge-medium{background:#fef3c7;color:#b45309}.admin-badge.badge-low{background:#f3f4f6;color:#4b5563}@media(max-width:600px){.hire-admin-editor{grid-template-columns:1fr}.hire-admin-editor h3{grid-column:auto}.hire-admin-drawer>header,.hire-admin-drawer>footer{padding:14px}}`}</style>
  </div>;
}
